name: Build Hexa OS ISO (Fast)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y nasm xorriso grub-pc-bin mtools gcc g++ make

    - name: Build Hexa OS
      run: |
        make clean
        make all

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hexa-os-iso
        path: hexa.iso
