name: Build Hexa OS 64-bit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt update && sudo apt install nasm qemu-system-x86 gcc binutils make -y

      - name: Build Hexa OS
        run: make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexaos64
          path: hexaos64.bin
