name: Build Hexa OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make nasm grub-pc-bin xorriso qemu-system-x86

      - name: Build Hexa OS
        run: |
          make clean
          make all

      - name: Test Hexa OS in QEMU (optional)
        run: |
          make run

      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: hexa-os-iso
          path: hexa.iso
