name: Build Hexa OS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt install nasm gcc binutils qemu-system-x86 -y

      - name: Build Hexa OS
        run: make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexaos
          path: hexaos.bin
